name: Run tests

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '11.x'
      -
        name: Install dependencies
        run: npm install
      -
        name: Run tests
        run: npm run test:unit
